### ISSUE TITLE
The installed yosys package is obsolete

### ISSUE THREAD

**Issue by tgorochowik** [SymbiFlow/sv-tests#1127]
After https://github.com/SymbiFlow/conda-packages/commit/cde6ba07930dd0ad004c7477aa357369a69cff51 was introduced, the package has been renamed from `yosys` to `symbiflow-yosys` - the `yosys` [package](https://anaconda.org/symbiflow/yosys) is still available but is not updated anymore.

**Comment by mithro** [comment]
@tgorochowik - I think we still want to have a yosys package which is just stock, unmodified, upstream yosys?

FYI - @PiotrZierhoffer

**Comment by tgorochowik** [comment]
To be honest I thought we do use stock yosys, but it turns out we never did. I agree that the stock package would be preferred here.

**Comment by caryr** [comment]
It looks like yosys was updated in the repo a couple days ago.

**Comment by tgorochowik** [comment]
Should be ok now
