### ISSUE TITLE
Use externally stored logs in report page

### ISSUE THREAD

**Issue by piotr-binkowski** [SymbiFlow/sv-tests#115]
As the test suite gets bigger, storing all the logs in the `report.html` file starts to create issues with the resulting file size (currently around 12MB) and performance.
Maybe loading the logs from external storage in a dynamic way could help with that.

**Comment by hzeller** [comment]
Just a link to the logfile is sufficient. The logfiles are all relative to the report.html, so a simple link to the logfile, loaded in a separate frame is all it needs.
