### ISSUE TITLE
Including gh-pages branch in this repo makes it *huge* (and thus very slow to download)

### ISSUE THREAD

**Issue by svenka3** [SymbiFlow/sv-tests#1179]
Hello,
  I am trying a fresh git clone of sv-tests on a Linux laptop (not very high-end, but does run EDA tools and is connected to highspeed Ethernet (Tried WiFi first, then moved to Ethernet). The process seems to take multiple hours > 4 hours. Is this common? I am sure it is first-time-only issue, later should be faster, but just wanted to check with others. Attaching a screenshot.

Any comments appreciated.

Thanks
Srini

![IMG_20201128_172147](https://user-images.githubusercontent.com/13112667/100515223-6a20e080-31a0-11eb-8389-b0cfb1a5e433.jpg)

**Comment by mithro** [comment]
@svenka3 - I would not expect that...

**Comment by mithro** [comment]
Oh, I see what is going on.

**Comment by mithro** [comment]
```
tansell:~/tmp$ time git clone https://github.com/SymbiFlow/sv-tests.git --single-branch --branch master
Cloning into 'sv-tests'...
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 11663 (delta 0), reused 1 (delta 0), pack-reused 11662
Receiving objects: 100% (11663/11663), 5.08 MiB | 12.21 MiB/s, done.
Resolving deltas: 100% (6744/6744), done.

real    0m1.559s
user    0m0.603s
sys     0m0.266s
```

The issue is the `gh-pages` branch is *massive*, like >1gb.

**Comment by mithro** [comment]
I think we probably need to move the gh-pages into its own repository?

**Comment by mithro** [comment]
@hzeller - What are your thoughts?

**Comment by mithro** [comment]
I tried to see if there is a way to make `git  clone` to ignore the `gh-pages` branch by default when cloning, but that doesn't seem to be supported.

I don't think we want to require people to run a special `git clone` command, as people won't notice they have to.

I think the steps would be to create a `sv-tests-output` repository, push the `gh-pages` to that repository and update the scripts to push there, remove the `gh-pages` branch from this repo and finally create a *new* `gh-pages` branch in this repository which redirects to the new https://symbiflow.github.io/sv-tests-output location?

**Comment by mithro** [comment]
I have done the following;
 * created an [sv-tests-results repository](https://github.com/SymbiFlow/sv-tests-results).
 * push the current contents of sv-tests-results's gh-pages branch to the gh-pages result there.
 * setup github pages on the sv-tests-results repo
 * created a gh-pages-redirect branch in this repo which redirects from https://symbiflow.github.io/sv-tests to https://symbiflow.github.io/sv-tests-results
 * made the gh-pages-redir branch the github pages branch for this repository

Final things to do are;
 * Update CI to push to the right locations
 * Remove the gh-pages branch from this repository

**Comment by mithro** [comment]
After merging #1242 and removing the gh-pages branch from this repository. This bug should hopefully be fixed.
