### ISSUE TITLE
Adding new tests - guide?

### ISSUE THREAD

**Issue by svenka3** [SymbiFlow/sv-tests#1180]
Hi,
  If I want to add few tests to this great repo, the procedure is described on the structure of the test. On the check-in/pull-request, is it the common flow as in:

https://jarv.is/notes/how-to-pull-request-fork-github/  (For instance)

Thanks
Srini

**Comment by tgorochowik** [comment]
Hello

Yes, the common workflow will work. Thank you for your interest and your future contributions :)

**Comment by svenka3** [comment]
Great, thanks!
