### ISSUE TITLE
Incorrect UVM tests

### ISSUE THREAD

**Issue by MikePopoloski** [SymbiFlow/sv-tests#1414]
There are a number of UVM tests that are invalid in that they inherit from a class without providing parameters to that class's constructor. Examples are uvm_agent_2, uvm_driver_2, uvm_monitor_2, etc. The fix is simple but I couldn't figure out where exactly these tests are coming from as I think they are generated from something.

**Comment by tgorochowik** [comment]
Those particular tests are indeed generated, this template is used: https://github.com/SymbiFlow/sv-tests/blob/master/conf/generators/templates/uvm-classes_2.json

**Comment by MikePopoloski** [comment]
Ah thanks, opened PR #1426

**Comment by MikePopoloski** [comment]
Looks like my patch fixed this.
