### ISSUE TITLE
fix the variances in column width in the report

### ISSUE THREAD

**Issue by tgorochowik** [SymbiFlow/sv-tests#1437]
Currently all the columns have different widths, it does not look very good:
![2021-04-07-111615](https://user-images.githubusercontent.com/8438531/113842152-af7a9d80-9792-11eb-878e-4aac1f78eb1c.png)

It would be nice to make all the widths equal. We need to think about what can  be done so the headers are still equally readable.

Maybe we could make them vertical? Or use some kind of an angle? Maybe it could use multiple lines and wrap? We need to experiment with that and see what works the best.

**Comment by hzeller** [comment]
I was wondering about that as well. I played with a 45 degree angle once (there are some [CSS hacks for that](https://css-tricks.com/rotated-table-column-headers/)), and it wasn't looking too bad and it can make things much more compact.

**Comment by Prahitha** [comment]
I've tried a couple of options, please let me know which one would suit best. Thanks!

![angle](https://user-images.githubusercontent.com/44160152/114308434-9f9bea00-9b01-11eb-805c-a36ec9d74023.png)
![nowrap](https://user-images.githubusercontent.com/44160152/114308436-a296da80-9b01-11eb-882e-30b40e9d55e0.png)
![wrap](https://user-images.githubusercontent.com/44160152/114308440-a9255200-9b01-11eb-8150-2779ed1bab69.png)
https://user-images.githubusercontent.com/44160152/114308437-a62a6180-9b01-11eb-9ab8-8113a72c560f.mp4

**Comment by tgorochowik** [comment]
Those look really nice! Thank you for your work!

My vote goes for the 45 angle one. In the final version we will have to make sure the "sort" icon is aligned to the end of the name nicely (currently it seems to be at a constant position and is covered by the text in some cases).

What do you think @hzeller ?

**Comment by Prahitha** [comment]
Thank you for the feedback! Also, I was wondering if it would be okay to split the word (for the wrap option), i.e, replace the underscore with a space):
`<a class="tool_link" target=_blank href='{{ report[tool]["url"] }}'>{{ tool.lower() }}</a>` -> `<a class="tool_link" target=_blank href='{{ report[tool]["url"] }}'>{{ tool.replace("_", " ").lower() }}</a>`
I think this will make the word-break look cleaner.

**Comment by hzeller** [comment]
+1 to the 45 degree version. That looks very nice and will always work; which is harder for the wrap version to make look pretty in all circumstances.

The up/down sorting arrow thing might be something that I'd intuitively expect not to be 'up in the air' next to the text, but more  aligned with the top of the table, upright; a bit like this:

![fourtyfive](https://user-images.githubusercontent.com/140937/114486934-8ce9e980-9bc3-11eb-968f-fcd8e503c707.png)

Hopefully that can be implemented without too much of a CSS scramble

**Comment by tgorochowik** [comment]
This is already implemented, closing.
