### ISSUE TITLE
Please add me to the contributor list

### ISSUE THREAD

**Issue by alaindargelas** [SymbiFlow/sv-tests#1513]

**Comment by mithro** [comment]
Can you just send a pull request adding yourself to the `AUTHORS` file at https://github.com/SymbiFlow/sv-tests/blob/master/AUTHORS ?

**Comment by mithro** [comment]
@alaindargelas - We use a "fork and pull" model of development. You push to your own fork of the sv-tests and send a pull request from that. 

See https://gist.github.com/Chaser324/ce0505fbed06b947d962 and https://reflectoring.io/github-fork-and-pull/

**Comment by alaindargelas** [comment]
Got it. Thanks!
