### ISSUE TITLE
Error when downloading the tnoc submodule

### ISSUE THREAD

**Issue by Prahitha** [SymbiFlow/sv-tests#1553]
![Screenshot (26)](https://user-images.githubusercontent.com/44160152/119783717-1bec6000-beeb-11eb-8f50-127f71fe1f3e.png)

**Comment by taichi-ishitani** [comment]
Hi @tgorochowik 
I often edit repositories added as submodules directly so I prefer `git@` protocol to `https`.

**Comment by mithro** [comment]
By default you should use https and then use `insteadOf` to change what is used https://gist.github.com/Kovrinic/ea5e7123ab5c97d451804ea222ecd78a / https://git-scm.com/docs/git-config

**Comment by taichi-ishitani** [comment]
Hi,
I've changed TNoC's submodule config according to advice from @mithro .

**Comment by taichi-ishitani** [comment]
> We can close this issue after updating the submodule

Should I create a PR to update TNoC?

**Comment by tgorochowik** [comment]
Please do! (dependabot should have updated it but it seems it didn't)

**Comment by taichi-ishitani** [comment]
I've created PR #1567 for this issue.
