### ISSUE TITLE
report: Have 'total' count row of successful tests vs. overall tests.

### ISSUE THREAD

**Issue by hzeller** [SymbiFlow/sv-tests#164]
It would be good if we'd have a row that shows the 'totals' of all tests for a particular tool, e.g. passing `117/573`. This is good for the `TL;DR` situation :)

This could be easily achieved by counting every test also towards a 'total' tag (though the row with the total count then needs to be printed a bit differently as we don't want the cells in that row to be clickable).

**Comment by tgorochowik** [comment]
I think it would also make sense to add a summary/total count of tags for which all the tests passed (instead of counting all individual tests).
