### ISSUE TITLE
report: The 'close' button is currently broken

### ISSUE THREAD

**Issue by hzeller** [SymbiFlow/sv-tests#184]
[context: current head https://symbiflow.github.io/sv-tests/ report, Chrome 75.0.3770.100]

The gray 'close' button in the corner of the "hover-screen" is currently doing nothing (which means it is hard to see the lower part of the main table as it is scrolling 'behind'.

(Maybe we can just have the main table not behind but simply in a split frame above, then we don't need the hover-screen closeable?).

**Comment by tgorochowik** [comment]
@hzeller a fix has been already merged and will be deployed shortly.

In the meantime, as a workaround you can click on the currently selected cell in the main table to "unselect" it.
