### ISSUE TITLE
See which riscv cores could be added as a test case

### ISSUE THREAD

**Issue by tgorochowik** [SymbiFlow/sv-tests#217]
The list is here: https://github.com/riscv/riscv-cores-list

**Comment by mithro** [comment]
We should basically do a `where Primary Language == SystemVerilog sort by license`.

Quick look it seems like the following would be good targets;

 - [ ] Ariane - https://github.com/pulp-platform/ariane
 - [ ] SCR1 - https://github.com/syntacore/scr1
 - [ ] Taiga - https://gitlab.com/sfu-rcl/Taiga

**Comment by tgorochowik** [comment]
All of them are [there](https://github.com/SymbiFlow/sv-tests/tree/13d24b897bf4f908b1425345dc752fbc3f1ea251/third_party/cores). I think this can be closed now.
