### ISSUE TITLE
Record parsing walltime metric ?

### ISSUE THREAD

**Issue by hzeller** [SymbiFlow/sv-tests#237]
Some tools might be good, but also slow to process the input.

It might be worthwhile determining the parse-time of each of these tools. Maybe the `BaseRunner` can extract some metric how long the execution time of the binary took and add that to the output metrics in the logfile (Given that we run this with `popen()`, we should of course also make sure that grabbing the output doesn't delay the process too miuch)

For smaller files, this would mostly record the overhead of starting the tools (and, alas, also will be a very noisy signal). For larger tests that process some larger input (e.g. the various cores), this could give a hint about the compile-time.

For reporting, we have to see what makes most sense; maybe initially just a total runtime at the bottom summary line (because the individual run-times are too noisy, but the overall time might somewhat give an idea).

(we need to be aware that there can be all kinds of skews when made with `make -j n`, so we should make sure to only use a `n` from `[1 .. smaller than number of available cores]` to have a somewhat useful output)

**Comment by tgorochowik** [comment]
This is already implemented
