### ISSUE TITLE
Create a how to document for "adding a new parser for testing"

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/sv-tests#326]

**Comment by drom** [comment]
I guess we should discuss if it is all about SystemVerilog parsers?
Typical SystemVerilog frontend should include:

* Preprocessor
* Parser
* Semantic Analyzer 

I think that we would need to provide a way to add a new tool covering one or several of these steps. Tests need to contain information about at what stage it could be fed into the chain and at what stage it should pass/fail.

**Comment by mithro** [comment]
I think that is a good start. I do think there are even a few more levels like;
 * Synthesis
 * Simulation
