### ISSUE TITLE
Add moore to test suite

### ISSUE THREAD

**Issue by fabianschuiki** [SymbiFlow/sv-tests#339]
I absolutely love your compliance test suite. It's an absolutely excellent and necessary idea! Is there any chance to add the [moore] compiler to it? Any guidance on how to contribute would be awesome!

[moore]: http://llhd.io/

**Comment by mithro** [comment]
If the moore compiler is open source, then we can definitely add it!

The first step would be to get your compiler into our conda packages at https://github.com/SymbiFlow/conda-packages

Then follow the examples in https://github.com/SymbiFlow/sv-tests/pull/316 or https://github.com/SymbiFlow/sv-tests/pull/249

**Comment by fabianschuiki** [comment]
> If the moore compiler is open source, then we can definitely add it!

It is! I'll add a corresponding package to `conda-packages` and the necessary additions to this repo in a PR.

**Comment by fabianschuiki** [comment]
Will be done once #340 lands.
