### ISSUE TITLE
Add link to the sv-test GitHub repository from report

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/sv-tests#415]
If you are at https://symbiflow.github.io/sv-tests it is hard to get to know it is coming from the github repo at https://github.com/SymbiFlow/sv-tests

**Comment by tgorochowik** [comment]
For now it is possible to get there only via this tiny link in the footer. I guess we could add some more detailed info about this at the very top of the page.

**Comment by tgorochowik** [comment]
This is already implemented, the top header is clickable, closing.
