### ISSUE TITLE
Split each runner into it's own Travis build stage

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/sv-tests#425]
https://docs.travis-ci.com/user/build-stages/

See 
![image](https://user-images.githubusercontent.com/21212/68638441-6f888b80-04b6-11ea-94dd-054a53873178.png)

**Comment by tgorochowik** [comment]
Implemented in https://github.com/SymbiFlow/sv-tests/commit/6d04919cebb2c1403b248a613f65d9cc1b0fc5e9
