### ISSUE TITLE
A broken basejump_stl submodule causes our travis to fail

### ISSUE THREAD

**Issue by tgorochowik** [SymbiFlow/sv-tests#427]
See: https://github.com/bespoke-silicon-group/basejump_stl/issues/187

There is also some discussion in #426.
Generally we do not want to disable fetching the submodules completely.

We should either find a way to select the submodules to clone by hand (probably not a good idea considering long-term), or allow travis to continue if some modules fail to clone (although this should probably be somehow indicated in the report - we don't want this to happen quietly).

**Comment by hzeller** [comment]
Relevant pull-request to watch: https://github.com/bespoke-silicon-group/basejump_stl/pull/188

**Comment by mithro** [comment]
This seems to be fixed now.

**Comment by tgorochowik** [comment]
It is, both with a workaround in our repo and in mainline basejump.
