### ISSUE TITLE
Use Verilator --Wpedantic flag

### ISSUE THREAD

**Issue by wsnyder** [SymbiFlow/sv-tests#441]
Some tests fail because Verilator is nice to users.  For example allows "reg global" because this was hitting a lot of real code before SV 2017.   Therefore some IEEE tests need to operate differently.

Please update the verilator submodule to the latest.

Then you'll see I've followed the lead of GCC and added a --Wpedantic switch, please use this flag on all of your testing of IEEE tests, but not of real projects (which might rely on extensions above IEEE).

Not sure how to only apply it to the right tests or would give you a patch.  Thanks

**Comment by mithro** [comment]
I believe this was fixed in #506?
