### ISSUE TITLE
Add the actual command that was executed to the report

### ISSUE THREAD

**Issue by tgorochowik** [SymbiFlow/sv-tests#637]
Add the actual command that was executed to the report (where applicable - some of the runners are not running external tools, so add a note there instead).

We could add that to the log pane just after the test parameters and before the logs.
This should make it easier to reproduce the test run outside sv-tests.

CC @alainmarcel

**Comment by hzeller** [comment]
@alainmarcel Does this look good ? It now allows to see the full command-line, ready to copy/paste for manual experiments
e.g. https://symbiflow.github.io/sv-tests/#Surelog|ariane|ariane

**Comment by alainmarcel** [comment]
Perfect!Thanks

Sent from Yahoo Mail on Android 
 
  On Tue, Mar 10, 2020 at 11:27, Henner Zeller<notifications@github.com> wrote:   
@alainmarcel Does this look good ? It now allows to see the full command-line, ready to copy/paste for manual experiments
e.g. https://symbiflow.github.io/sv-tests/#Surelog|ariane|ariane
