### ISSUE TITLE
Add filter to Surelog return code for pass/fail criteria

### ISSUE THREAD

**Issue by alainmarcel** [SymbiFlow/sv-tests#663]
Surelog executable returns the following error codes:

0 - OK
1 - Fatal error 
2 - Syntax error
4 - Semantic error

Only consider 0, 1, 2, ignore 4 for sv-tests.

**Comment by hzeller** [comment]
To clarify, this is a bit-mask, right ? So we essentially need to see if `(return_code & 0x03) != 0` to determine error.

**Comment by alainmarcel** [comment]
Correct

**Comment by hzeller** [comment]
I just looked at this: I have only seen return codes 0, 1, and 3, nothing larger than that.

**Comment by alainmarcel** [comment]
I disabled 4 until you get your change in ;-)Can I turn it back on? (it is commented out in Surelog/src/main.cpp)Alain 

    On Friday, February 28, 2020, 11:43:20 AM PST, Henner Zeller <notifications@github.com> wrote:  
 
 
I just looked at this: I have only seen return codes 0, 1, and 3, nothing larger than that.

**Comment by hzeller** [comment]
Not yet, but I am working on a filter currently.
