### ISSUE TITLE
Convert all test cases from should_fail to should_fail_because

### ISSUE THREAD

**Issue by ahegazy** [SymbiFlow/sv-tests#688]
As per issue #449  and PR #687 : 

Right now we have 1702 test case
- 1582: test case with should_fail: 0
- 120: test case with should_fail: 1

so we have to 
- [x] ~remove should_fail: 0 from all test cases and generators PR #689 ~
- [ x] ~Replace should_fail: 1 with should_fail_because: + reason in all test cases and generators PR #702 ~
- [ x] ~Update the README.md#adding-new-test-cases section PR #702 ~

**I suggest that:**
- should_fail: 0 be all removed at once using simple sed command.
- should_fail: 1 files, the reason normally is written in the description: tag, write a script to copy whatever in the description to the the should_fail_because: tag.

and as discussed in the comment of #449 
> but the shoul_fail: 1 ones probably should be done manually or script-converted and then checked against the SystemVerilog specification, ideally to always reference the spec.

**Comment by hzeller** [comment]
So with this, we can close #449 right ?

**Comment by ahegazy** [comment]
> So with this, we can close #449 right ?

well, It was closed back then in march when the #689 and #702 were merged, I don't know why it was opened again.

**Comment by hzeller** [comment]
Maybe it only closed this #688 but not #449. Anyway, just closed it. Thanks!
