### ISSUE TITLE
Split moore into separate parser and compiler test

### ISSUE THREAD

**Issue by fabianschuiki** [SymbiFlow/sv-tests#690]
The moore parser can be used as a standalone library. Would it make sense to split `moore` into `moore-parse` and `moore`, such that the parser and code generator can be assessed separately?

**Comment by mithro** [comment]
@fabianschuiki - That sounds like a decent idea. Is that something you have the time to do?

**Comment by fabianschuiki** [comment]
@mithro Absolutely, will open a PR. Just wanted to run the idea by you first.

**Comment by fabianschuiki** [comment]
Opened #691.
