### ISSUE TITLE
The earlgrey test should scan for source files dynamically

### ISSUE THREAD

**Issue by tgorochowik** [SymbiFlow/sv-tests#764]
See #748 and the fix in #761 

Ideally we should use a python `glob` in the test generator to find all the needed files (instead of having the list of files in a config file):
https://github.com/SymbiFlow/sv-tests/blob/d60466dd1b2b778bfd67e425b4082378f227ba21/generators/earlgrey#L42-L46

Note that we may actually need to use both approaches to keep including the uvm stuff.

Otherwise it will keep breaking with changes to the submodule (another question is why the bumped submodule was even merged by dependabot)

**Comment by tgorochowik** [comment]
Note: this may be also applicable to other tests for which we store the list of source files in a config file.

**Comment by hzeller** [comment]
@kgugala suggested to possibly have a fusesoc run generate the directory structure and the filelist + defines command line. Karol can you find someone who could put this in the sv-test run ?

This will also be useful to keep the OpenTitan tets up-to-date in [Surelog]( https://github.com/alainmarcel/Surelog) and [uhdm-integration](https://github.com/alainmarcel/uhdm-integration) tests.
