### ISSUE TITLE
Investigate if outputting xUnit format makes sense

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/sv-tests#77]
If sv-tests could output xUnit XML, then the test results would be compatible with a wide range of tools. Could mean we can ditch creating our own HTML frontend?

> XML files in xUnit format can be consumed by a wide range of tools, such as build systems, IDEs and continuous integration servers.
>
> ## Schema
> 
> There are many schemas with minor differences.
> We use one that is compatible with Jenkins xUnit plugin, a copy is
> available under `tests/vendor/jenkins/xunit-plugin/junit-10.xsd` (see attached license).
> You may also find these resources useful:
> 
> - https://stackoverflow.com/questions/4922867/what-is-the-junit-xml-format-specification-that-hudson-supports
> - https://stackoverflow.com/questions/11241781/python-unittests-in-jenkins
> - [Jenkins (junit-10.xsd)](https://github.com/jenkinsci/xunit-plugin/blob/master/src/main/resources/org/jenkinsci/plugins/xunit/types/model/xsd/junit-10.xsd)
> - [JUnit-Schema (JUnit.xsd)](https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd)
> - [Windyroad (JUnit.xsd)](http://windyroad.com.au/dl/Open%20Source/JUnit.xsd)
> - [a gist (Jenkins xUnit test result schema)](https://gist.github.com/erikd/4192748)

**Comment by piotr-binkowski** [comment]
I've checked the xUnit XML format and the format itself supports storing all the information that we use (runner log, test status, basic hierarchy - chapters, subchapters).

But the tools I found for visualizing the XML doesn't seem to produce results as readable as our current reports, especially when it comes to comparing different tools.
I tried [xunit-to-html](https://github.com/Zir0-93/xunit-to-html) as it was the most promising in my opinion and the results are shown below:
![chapter-test-tool](https://user-images.githubusercontent.com/45362851/64867287-65c0e400-d63d-11e9-89ad-7adb21a619d2.png)
![tool-chapter-test](https://user-images.githubusercontent.com/45362851/64867289-66597a80-d63d-11e9-95e3-4eb38c89c29b.png)
I prepared mock XML files using two approaches, first one groups test results by chapters and the other one groups them by runner.

I also checked the [xunit-viewer](https://github.com/lukejpreston/xunit-viewer) but the [demo](https://lukejpreston.github.io/xunit-viewer/) provided seemed like it also wouldn't suit our needs.

Maybe someone could suggest a more suitable tool for processing those XML reports

**Comment by mithro** [comment]
You should just be able to feed your XML into xunit-viewer and see what it looks like?

**Comment by mithro** [comment]
Maybe https://github.com/inorton/junit2html/blob/master/README.md ?

**Comment by mithro** [comment]
Maybe https://github.com/extent-framework/extentreports-dotnet-cli

**Comment by piotr-binkowski** [comment]
I also tried to use the `extentreports-dotnet-cli` tool but I couldn't get it to work on my PC, ie. running
> [pbinkowski@arch xunit]$ mono extent.exe -i /home/pbinkowski/projects/systemverilog/xunit/test.xml -o /home/pbinkowski/projects/systemverilog/xunit/ext/
> 
> extentreports-cli initializing ...
> Parsing test runner result file '/home/pbinkowski/projects/systemverilog/xunit/test.xml' ...
> The html report will be output to the folder '/home/pbinkowski/projects/systemverilog/xunit/ext/'.
> Report for '/home/pbinkowski/projects/systemverilog/xunit/test.xml' is complete.
> extentreports-cli finished.

would leave the output directory empty while at the same time log looks like everything went fine

**Comment by piotr-binkowski** [comment]
I think we can close this since we ended up using a custom generated HTML + `.csv` report
