### ISSUE TITLE
conf/lrm.conf should be used for descriptive annotations in report.html

### ISSUE THREAD

**Issue by hzeller** [SymbiFlow/sv-tests#84]
The config file that maps sections to descriptions, but right now, this file is not used much.

The `sv-report` uses it to create a list of potential test case classifications, but we should possibly also use the information there to annotate the output in the reports. For instance having 11.4.7 annotated as `11.4.7  Logical operators` is probably very helpful.

**Comment by tgorochowik** [comment]
@hzeller the chapter name/description is currently shown on mouse overlay, see: #30 

Would you prefer it to be constantly shown? For example as an additional column?

**Comment by hzeller** [comment]
Yes, I think an additional column would be great.
