### ISSUE TITLE
Automatically determine file list for Ariane test

### ISSUE THREAD

**Issue by piotr-binkowski** [SymbiFlow/sv-tests#937]
Currently Ariane test uses hardcoded list of files that can become outdated after Ariane update (#936)
It would be best to use FuseSoC to prepare a list of files just like we did in case of Earlgrey (#875) since Ariane [seems to have FuseSoC support](https://github.com/openhwgroup/cva6/blob/2d814452094b3e20897e2362771d70024a610651/ariane.core)

**Comment by tgorochowik** [comment]
Done in #1275
