### ISSUE TITLE
Runners not updated to supply defines

### ISSUE THREAD

**Issue by MikePopoloski** [SymbiFlow/sv-tests#949]
It seems like tests were added that require command line macro definitions, but then only the verilator runner was updated to provide them. Shouldn't the rest of the runners be updated as well?

**Comment by tgorochowik** [comment]
Yes, certainly!
We actually added the tests that require macro definitions much earlier (mostly the cores that we are testing) and we lacked supplying the required definitions to tools. We only recently added support for supplying the tools with the definitions and Verilator was the base for the experiments.

We certainly need to add these for the remaining runners (where applicable).
