### ISSUE TITLE
Still can't easily get to tested projects...

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/sv-tests#957]
Was at https://symbiflow.github.io/sv-tests/ and still couldn't figure out how to get to the slang repo for example.

Didn't we also land something which takes you to the source for the test repos (like black-parrot and such)?

**Comment by hzeller** [comment]
Ideally, the headers would be clickable pointing to the projects (right now, they allow for some sort of sorting functionality, though not entirely sure how useful that is).
To find a link to the project it is a bit more tricky currently: click on one test case, then you see the log at the bottom left of the screen. The parser itself is in the headline a link back to the project. A bit hard to find.

For links to tested external projects, I have #934 open.
