### ISSUE TITLE
Migrate SweRV to use FuseSoC generator

### ISSUE THREAD

**Issue by piotr-binkowski** [SymbiFlow/sv-tests#998]
SweRV still uses a custom generator script and it seems that it's file list is outdated (#894)
It should be fairly easy to migrate it to use [FuseSoC generator](https://github.com/SymbiFlow/sv-tests/blob/master/generators/fusesoc) since the core has [FuseSoC config](https://github.com/chipsalliance/Cores-SweRV/blob/master/swerv.core) and with FuseSoC we won't need to manually update the file list

**Comment by joannabrozek** [comment]
Fixed in #1300, #1341 and #1344.
